[tool.poetry]
name = "byu-recan"
version = "0.0.0"
description = "Analyze IDE recording files."
authors = ["Gordon Bean <gbean@cs.byu.edu>", "Robert Greathouse <robbykap@byu.edu>"]
license = "MIT"
packages = [{ include = "recan" }]

[tool.poetry.dependencies]
python = "^3.12"
Jinja2 = "^3.1.6"
pydivsufsort = "^0.0.20"
PyYAML = "^6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
poetry-version-from-file = "^1.1.0"

[tool.poetry.plugins.version-from-file]
enabled = "true"
file = "recan/VERSION"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.poetry.scripts]
recan = "recan.main:entry"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-version-from-file"]
build-backend = "poetry.core.masonry.api"
